project_id = "padaqqnkkucudkhjscgk"

[functions.process-document]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.save-notebook-entry]
verify_jwt = true

[functions.update-progress]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true